- lib/upstream/zookeeper.js
> **NOTE:** Please put proposed changes into tiny commits, so that they can be reverted or modified without lots of chaos.
> Initial code review

- lib/decoders/disk.js
- lib/decoders/geojson.js
- lib/decoders/index.js
- lib/decoders/kml.js
- lib/decoders/kmz.js
- lib/decoders/layer.js
- lib/decoders/merger.js
- lib/decoders/shapefile.js
- lib/service.js
- lib/services/spatial.js
- lib/services/summary.js
- test/disk.js
- test/kmz.js
- test/merger.js
- test/shapefile.js
- test/spatial.js
* Added disk class which listens to request lifecycle
* Allocations are done via this thing and cleaned up
when the request finishes
* Added test/disk.js
* Moved test files around to take advantage of this
> File allocation tracking

- lib/boot.js
- lib/config/config.js
- lib/config/index.js
- lib/config/test.js
- lib/decoders/index.js
- lib/decoders/kml.js
- lib/decoders/layer.js
- lib/decoders/shapefile.js
- lib/decoders/transform.js
- lib/router.js
- lib/service.js
- lib/services/spatial.js
- lib/services/summary.js
- lib/upstream/core.js
- lib/upstream/zookeeper.js
- lib/util/logger.js
- package.json
- test/geojson.js
- test/spatial.js
- test/zk-client.js
* Remove all the console.logs
* Added bunyan
* Added log wrapper
* req and response have log methods, which eventually will log the request id
* not sure of a good way to test because node doesn't have a way to capture IO
> Add logging

- README.md
- lib/config/config.js
- lib/config/dev.js
- lib/config/index.js
- lib/config/test.js
- lib/decoders/disk.js
- lib/decoders/index.js
- lib/decoders/kml.js
- lib/decoders/kmz.js
- lib/decoders/layer.js
- lib/decoders/merger.js
- lib/decoders/shapefile.js
- lib/router.js
- lib/service.js
- lib/services/spatial.js
- lib/services/summary.js
- lib/services/version.js
- lib/soql/array.js
- lib/soql/mapper.js
- lib/soql/soql.js
- lib/upstream/core.js
- lib/upstream/zookeeper.js
- lib/util/bbox.js
- lib/util/logger.js
- package.json
- test.sh
- test/smoke/shp-http.js
- test/unit/soql.js
* remove the .bind(this) on arrow functions
* fix all the jshint warnings
* add jshint to jankins test
> General cleanup, refs #11

- lib/decoders/layer.js
- lib/decoders/shapefile.js
- test/smoke/shp-http.js
- test/unit/spatial.js
- test/unit/summary.js
* Because Geotools does what it does best and crashes
while attempting to parse the Well Known Text
> Replace projection WKT with simple string name

- .gitignore
- docker/Dockerfile
- docker/README.md
- docker/ship.d/run
- lib/config/dev.js
- lib/config/prod.js
- lib/config/test.js
- lib/upstream/zookeeper.js
- scripts/postinstall.sh
* Wrote a dockerfile
* Wrote a prod config
* Updated docker readme
* Updated postinstall script to not run for docker builds
> Dockerize the service

- lib/router.js
- lib/services/summary.js
- test/unit/spatial.js
- test/unit/summary.js
* When summary was empty, it 404'd on replace
* Made PUT route URL parameter optional
* Fixed content-length check so it doesn't collide
with the content-length that the SimpleHTTPClient
adds
> Refs CORE-6930

- docker/ship.d/run
- es6-lib/config/config.js
- es6-lib/config/prod.js
- es6-lib/index.js
- es6-lib/util/metrics.js
- package.json
* Add OnFatalError (ofe) handler
* Update run script to copy crash.log and heapdump* to sandbox
* Add GC watcher to metrics
> Diagnostics things

- es6-lib/decoders/kml.js
- es6-lib/decoders/kmz.js
- es6-test/smoke/flow-control.js
* Not extended attributes
* Also fix a race condition where the kmz wrapping stream
is ended and the kml stream pushes onto it
> Name and Description are children of Placemark

- es6-lib/decoders/kml.js
- es6-lib/util/metrics.js
- es6-test/fixtures/smoke/noaa.kml
- es6-test/smoke/decoders.js
* Had made this change for the start tag
event, also need it for the end tag event.
Refs EN-400
> Fix name and description KML special cases

- es6-lib/decoders/kml.js
- es6-lib/services/spatial.js
- es6-test/fixtures/with_nulls.kml
- es6-test/unit/kml.js
* Added a test too
Refs EN-400
> Convert empty elements to null on KML path

- es6-lib/decoders/kmz.js
> Only add a drain listener when changing flow state

- es6-lib/decoders/kml.js
- es6-test/fixtures/type_guessing.kml
- es6-test/unit/kml.js
- es6-test/unit/shapefile.js
- mem.ldjson
> Remove use of parseFloat in KML decoder

- docker/Dockerfile
- docker/runit/run
- es6-lib/config/test.js
- es6-lib/index.js
- es6-lib/router.js
- es6-lib/service.js
- es6-lib/services/summary.js
- es6-lib/util/metrics.js
- es6-test/unit/metrics.js
- es6-test/unit/summary.js
* Added a metrics class which samples the memory
* Added a middleware bit to the main endpoints to
track http response codes
* Remove the interval spam
Refs EN-3115
> Add a /metrics endpoint

- es6-lib/upstream/core.js
- es6-test/services/mock-core.js
- es6-test/unit/core-client.js
> Set the user-agent for core reqs

- es6-lib/config/test.js
- es6-lib/decoders/kml.js
- es6-lib/decoders/wgs84-reprojector.js
- es6-lib/soql/geom.js
- es6-test/smoke/decoders.js
- es6-test/unit/geojson.js
- es6-test/unit/kml.js
- es6-test/unit/shapefile.js
- es6-test/util.js
* Point state carried over to multipolygon state which
screwed up the arity of multipolygons in some cases
* Actual fix is in decoders/kml.js
* Added a bunch of checks in the unit and smoke tests
Refs EN-3725
> Adventures in mutable state

- es6-lib/config/config.js
- es6-lib/consumer.js
- es6-lib/service.js
- es6-lib/services/spatial.js
- es6-test/unit/iss-client.js
- es6-test/unit/spatial.js
* Unsubscribe from queue immediately
* End http app immediately
* Wait for all running imports to finish before exit
Refs EN-3503
> Hook signals for graceful shutdown

- bin/start.sh
- es6-lib/config/config.js
- es6-lib/services/spatial.js
- es6-lib/upstream/core.js
- es6-test/services/mock-core.js
- es6-test/unit/core-client.js
- es6-test/unit/spatial.js
* Merge the geo metadata with the view's
existing metadata
> EN-10428 Use existing view metadata

- es6-lib/errors.js
- es6-lib/tasks/translations.js
- es6-lib/upstream/iss.js
- es6-test/smoke/merger.js
- es6-test/unit/geojson.js
- es6-test/unit/iss-client.js
- es6-test/unit/kml.js
- es6-test/unit/kmz.js
- es6-test/unit/merger.js
- es6-test/unit/shapefile.js
- es6-test/unit/spatial-errors.js
- es6-test/unit/spatial.js
- es6-test/unit/summary.js
* Errors are now
{
eventType: actual-event,
info: {...params}
}
* fixed all the tests
* Fixed translation generator to make a title and description
> EN-10317 Make errors match di2

- es6-lib/errors.js
- es6-lib/soql/soql.js
- es6-test/unit/soql.js
* Also better error messages for when stuff goes wrong;
there is a change in core-misc to not mangle geo-import
errors
> EN-13240 Laundering the name twice made it invalid

- es6-lib/errors.js
- es6-lib/soql/soql.js
- es6-test/services/mock-core.js
- es6-test/unit/core-client.js
- es6-test/unit/soql.js
- es6-test/unit/spatial.js
* But broken in a way that it always passed without running
the tests!
* This fixes all the tests related to the spoofing user commit
> EN-10495 PR Builder was broken

- es6-lib/config/config.js
* It was leading to unexpected 4x4 mutation for the customer
> Kill the summary path

- es6-lib/services/summary.js
> add missing semicolons

- docker/Dockerfile
> Update dockerfile to bionic image.

- docker/Dockerfile
This reverts commit e851ba9523aa97eeab5d565fedc9103725a3ecb5.
> Revert "[noissue] use runit-nodejs-bionic-14x (#115)"

- .babelrc
- Makefile
- docker/Dockerfile
- package-lock.json
- package.json
- test.sh
Branch passes Cheetah tests on staging. This is a [revert](https://github.com/socrata-platform/geo-import/pull/121) that has been reviewed before.
> [EN-46573,EN-46612,EN-46611,EN-46576] upgrade babel
