lib/decoders/kml.js
lib/decoders/kmz.js
lib/decoders/shapefile.js
lib/router.js
test/fixtures/points_and_lines_multigeom.kml
test/kml.js
test/kmz.js

* Previous implementation assumed homogenous
collections in the MultiGeometry tag,
which is not a reasonable assumption since
KML allows you to do anything your heart desires.
* Added a point_and_line test in the test/kml.js
suite for this case.
* All the parsing handlers now return a tuple
*ahem array* of the state and N features to
emit on the stream, rather than a singel feature
to go on the stream. This allows emitting
different typed features when we're within
a multigeometry.
* Things are turned into multi* shape objects if
they exist within a multigeometry, even if there
is one. This tradeoff reduces extra complexity.

Add heterogenous multi geometry support to KML

---

lib/decoders/kml.js
test/fixtures/points_and_lines_multigeom_sans_schema.kml
test/kml.js

* there was a bug with KML when no schema was specified
* in the step from object -> SoQL conversion, it will now
attempt to choose a type when there is no schema supplied

Fix KML bug

---

lib/decoders/transform.js
lib/services/spatial.js
lib/upstream/core.js
test/services/mock-core.js
test/unit/spatial.js
test/unit/summary.js

* If the upsert fails, or column creation fails, clean up
the datasets that were initially created to put the data
into.
* Added tests, added delete endpoint in mock-core to mirror
core irl

Cleanup on import failure

---

README.md
lib/decoders/layer.js
lib/decoders/merger.js
lib/router.js
lib/services/spatial.js
lib/services/summary.js
lib/upstream/core.js
test/services/mock-core.js
test/unit/core-client.js
test/unit/merger.js
test/unit/spatial.js

* Replace shapefile 
* Added PUT route in router
* Added replace method in service/spatial.js
* Added _replaceLayers which 
* for any layers not in the blueprint, create them
* for layers in the blueprint, create a working copy
*  Delete the columns
* For all the layers, create the columns and perform the upsert
* tests in `unit/spatial.js`
* Accept blueprint as query param for which view to use as the working copy
* Pass layer names through to core via url params
* Added tests in spatial service and merger

Replace shape

---

lib/upstream/zookeeper.js

* when dealing with a large row, node blocks and the zk session
expires. node-zookeeper-client doesn't have reconnect logic,
so it has been added
* important to note that the `expired` state is a terminal
state for the client, so once it has expired, the client
needs to be torn down and a new one initialized

Reconnect to zk

---

es6-lib/decoders/kml.js
es6-lib/decoders/kmz.js
es6-lib/decoders/layer.js
es6-lib/decoders/ldjson.js
es6-lib/decoders/wgs84-reprojector.js
package.json

* through2 hardcodes the highwatermark
which is problematic for complex shapes
* ldjson stream uses through2, so drop that
as well
* re-implement ldjson stream in ldjson.js
* re-implement through2 reprojection that lived
in layer.js in wgs84-reprojector

Get rid of through2 lib usage

---

es6-lib/config/config.js
es6-lib/decoders/layer.js
es6-lib/decoders/merger.js
es6-lib/services/spatial.js
es6-lib/services/summary.js
es6-lib/soql/line.js
es6-lib/soql/multiline.js
es6-lib/soql/multipoint.js
es6-lib/soql/multipolygon.js
es6-lib/soql/point.js
es6-lib/soql/polygon.js
es6-test/unit/merger.js
es6-test/unit/soql-geom.js
es6-test/unit/spatial.js
es6-test/unit/summary.js

* Put a limit on the number of vertices
allowed per row.
* ST_Simplify queries against pg pin the CPU
on super complex rows, so until a solution
is found for that, we aren't going to allow
those sorts of datasets.
* Added tests

Refs EN-1306

---

es6-lib/decoders/kmz.js
es6-lib/decoders/layer.js
es6-lib/decoders/shapefile.js
es6-test/smoke/flow-control.js

* KMZ, Shapefile, and Layer all listen to downstream streams
to pause/unpause themselves. They didn't handle the case
where the downstream stream disappears mid-run. Now they
handle that case. They do not pause and buffer data, they
simply EOF
* Added tests in smoke/flow-control for these cases

Refs EN-1592

---

es6-lib/util/parser.js
es6-test/fixtures/empty_attrs.json
es6-test/unit/js-parser.js

* Fix a bug where the JS parser's stack got screwed up when
it encountered an empty object
* Added empty object test and fixture,
tested on real data

Refs EN-220

---

es6-lib/config/config.js
es6-lib/decoders/layer.js

* Fix is to not call srs.parse all the time.
Should be faster too, caching the parsed
spatial reference system objects.

Found the culprit of the leaked native memory

---

es6-lib/soql/line.js
es6-lib/soql/multiline.js
es6-test/fixtures/non-line-lines.json
es6-test/fixtures/non-line-multiline.json
es6-test/unit/geometry-transforms.js

* Soda-fountain rejects lines that only have a single point.
Some datasets in kml and geojson format have single points,
so this fix puts them in a form that the library used by
soda-fountain will accept
* Added tests
Refs EN-2061

Fix semantics of lines before upsert

---

es6-lib/services/spatial.js
es6-test/unit/spatial.js

* When a replace request was made, if an error was encountered,
it would clean up the layers rather than leaving them. We only
want this logic on the new dataset path because replacement
layers are working copies not new datasets.
* Updated tests
Refs EN-2456

Fix massive bug

---

es6-lib/decoders/layer.js
es6-test/smoke/kml-http.js

* Layer class method belongsIn was returning true when `this`
was a subset of the row comparing against, so it would erroneously
merge rows into layers that they didn't belong. This resulted
in incorrect files that were spilled to disk.
* The strange thing is that instead of a 400 Bad request from
the upstream server, it would just hang and give a socket
timeout.
Refs EN-1835

Found the actual problem

---

es6-lib/decoders/kml.js
es6-lib/decoders/layer.js
es6-test/fixtures/smoke/terrassa.kml
es6-test/smoke/decoders.js

* Placemarks don't need to have geospatial information, but
socrata expects them to so we need to ignore these
* Added smoke test with terrassa file which uncovered this
Refs EN-3725

Ignore non-spatial rows

---

es6-lib/consumer.js
es6-lib/services/spatial.js
es6-test/unit/spatial.js

* parallel cheetah tests uncovered a bug
where files were being cleaned up before they
should have because everyone was using the same ISS
instance, which emitted an end event for ISS rather
than the activity, causing all files to get collected.
* solution: everyone gets their own ISS

Fix the regression tests

---

es6-lib/decoders/geojson.js
es6-lib/decoders/kml.js
es6-lib/decoders/layer.js
es6-lib/decoders/transform.js
es6-lib/decoders/wgs84-reprojector.js
es6-lib/soql/date.js
es6-lib/soql/soql.js
es6-lib/soql/text.js
es6-test/fixtures/simple_points_dup_columns.json
es6-test/smoke/decoders.js
es6-test/smoke/merger.js
es6-test/unit/merger.js
es6-test/unit/shapefile.js
es6-test/unit/soql.js
es6-test/unit/summary.js

* The previous approach was bad and i feel bad
* This is a little better
* Added a test
* Fixed the gross tests which had double-underscored columns
* Also removed some unused imports

EN-6393: Fix column name laundering

---

docker/runit/run
es6-lib/errors.js
es6-lib/upstream/core.js

* set displayType in the updateMetadata
* makes views that fail to import stay as drafts
* fix a bug where error cleanup errors threw an error
* smaller memory size - prod monitoring suggests the container
is way too big

EN-7892 Set displayType

---

es6-lib/config/config.js
es6-lib/decoders/layer.js
es6-lib/decoders/merger.js
es6-lib/decoders/wgs84-reprojector.js
es6-test/fixtures/simple_lines.json
es6-test/fixtures/simple_multilines.json
es6-test/fixtures/simple_multipoints.json
es6-test/fixtures/simple_multipolygons.json
es6-test/fixtures/simple_polygons.json
es6-test/smoke/flow-control.js
es6-test/unit/merger.js

* Now rows with different CRSs get put in different layers.
This means we don't have to store each CRS+offset in each layer,
because layers have a single CRS.
* The original bug was for a 3million row dataset it would
allocate 3m CRS strings, which would kill the service
* Reworked tests as well
* have hetero/homogenous CRS layers in the merger unit test,
changed expectations of how many layers will be made
* made floating point checks not gross - wasn't causing problems
in practice but it's much nicer now.

EN-10642 Rework how crs's work

---

es6-lib/services/spatial.js
es6-test/unit/spatial.js

* Un-break geo-import replace
* it was updating the parent metadata
to point at the working copy fourfour
rather than the published one, which broke
things when the import was complet

Refs EN-11805

---

Makefile
es6-lib/decoders/layer.js
es6-lib/decoders/shapefile.js
es6-lib/decoders/wgs84-reprojector.js
es6-lib/services/spatial.js
es6-lib/soql/geom.js
es6-lib/util/bbox.js
es6-test/fixtures/empty_coords.json
es6-test/unit/shapefile.js
es6-test/unit/spatial.js
package.json

* Would get classified as a different layer
* The actual fix is in the rozap/shapefile library,
the same garbage that was happening with wrapping
polygons as multis was happening to lines. The logic
in the original library was bad so i changed it
* This then broke other things that assumed coordinates
existed - i fixed those, and added a test
* Un c++ified the node-srs dep, because mapbox
released a impl that just seems to work :yay:

EN-12855 Empty coordinate lists were breaking things

---

package.json

If this works, the PR builder should actually pass.

Fix mocha to version 3.5.3 as the 4.0.0 version doesn't exit tests

---

docker/Dockerfile

We are on node 14 so we shouldn't be using 10x anymore.

[noissue] use runit-nodejs-bionic-14x
